#!/bin/sh
echo "Starting app..."

SECRET_KEY=$SECRET_KEY \
DATABASE_URL=$DATABASE_URL \
FLASK_APP=$FLASK_APP \
FLASK_ENV=$FLASK_ENV \
flask db upgrade

SECRET_KEY=$SECRET_KEY \
DATABASE_URL=$DATABASE_URL \
FLASK_APP=$FLASK_APP \
FLASK_ENV=$FLASK_ENV \
flask seed all

exec env \
  SECRET_KEY=$SECRET_KEY \
  DATABASE_URL=$DATABASE_URL \
  FLASK_APP=$FLASK_APP \
  FLASK_ENV=$FLASK_ENV \
  gunicorn app:app